### ISSUE TITLE
[off-topic] - can we please have sage on pypi?

### ISSUE THREAD

**Issue by dimpase** [dhagrow/profig#20]
Dear Miguel,
Sage (aka SageMath, for purposes of not clashing with Sage the accounting software) is a [Python-based computer algebra system](https://github.com/sagemath/sage), see also https://www.sagemath.org/ - active since 2006.
On https://trac.sagemath.org/ticket/28796 we noticed that in 2018 (apparently) you set up https://pypi.org/project/sage/ - which is 
basically a placeholder, that only saw 1 release, and has no functionality.

As we are (finally...) [moving towards](https://trac.sagemath.org/ticket/30912) putting more parts of SageMath on pypi, it would be quite convenient for us to get hold of  https://pypi.org/project/sage/. Could we please have it?

cc: @embray @mkoeppe @williamstein @vbraun @saraedum @jhpalmieri

**Comment by dimpase** [comment]
We're following https://www.python.org/dev/peps/pep-0541/#how-to-request-a-name-transfer here.

**Comment by dhagrow** [comment]
Hello @dimpase. I willing to agree that you have a better claim on the name. Unfortunately I seem to have lost my 2fa codes for PyPI. I can look into transferring the name as soon as I recover access to my account.

**Comment by dimpase** [comment]
Thanks. There is no rush. In principle, you agreeing  to transfer the name is all PyPI needs to know to do the transfer.
